### ISSUE TITLE
Latest version flagged as malicious software by Chrome

### ISSUE THREAD

**Issue by Xuerian** [poma/Hotsapi.Uploader#38]
Blocks download.

**Comment by poma** [comment]
Can't reproduce

**Comment by Xuerian** [comment]
Well, I'd capture a video of it, but that's not cooperating apparently.

![](https://i.imgur.com/JZY2cW0.png)
![](https://i.imgur.com/3xVrJzC.png)
![](https://i.imgur.com/XyNEFh2.png)

**Comment by poma** [comment]
Well I guess someone has to send a false positive email to go google smart screen support, maybe I'll do it after holidays

**Comment by SC2Mitch** [comment]
It's not just google that's the problem, there's about 20 Malware vendors as well as a couple of Anti Virus vendors that are flagging for Trojan.GenericKD and Trojan.Reconyc, pretty sketchy to me. 
https://www.virustotal.com/#/file/f8df3691171b4b6996fad4b55e9694d311f57683a7418d52771bbc81d54bd133/detection

**Comment by poma** [comment]
Well source code is open and build server is public, anyone can check what this app does.

What happens is many antivirus companies tend to just flag most unsigned programs as malware and then wait for false positive emails from creator. I've experienced it before, lots of my simple as we're flagged until I bought a certificate for them. At first I've sent a bunch of those letters but now I don't have enough time. If someone from the community does it would be nice. Or if I get enough donations for digital signature it will solve this problem too.

**Comment by poma** [comment]
Since I now can reproduce it I'll try to experiment and remove parts of uploader to find out what exactly google doesn't like

**Comment by poma** [comment]
FYI last time AV software mass flagged uploader was because of its "start with windows" checkbox that was adding startup entry in registry. Apps that payed for certificate can do this without any problems.

**Comment by herrvigg** [comment]
It looks like false alarms but I suggest you remove anything that could be detected as malware, even if we lose some features such as "start with windows". Otherwise some people will lose faith in the app, spread the word and more will start not using it at all. Once you have found a good solution with the malware flags then you can restore these features.

**Comment by poma** [comment]
Apparently even reading "start with windows" setting from the previous version triggers antivirus software. I was hoping that if I guard it with a conditional (triggers only during settings upgrade) it will be enough, but I was wrong. Now "start with windows" setting will be lost and switched to "off" when upgrading from earlier versions (<=1.7). This removes false flag from Chrome and most antiviruses, at least for now until they decide that they don't like something else about the uploader.

By the way false flags are very common in the antivirus software, they routinely mass flag programs [placing burden of proving that it is a false positive on the developers](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/). And [this](https://www.pcworld.com/article/2883692/virustotal-tackles-false-positive-malware-detections-plaguing-antivirus-and-software-vendors.html) is how VirusTotal deals with it - notice how it is not about improving their algorithms but adding big guys to a whitelist so that they not make it to the news headlines by [flagging a part of Windows as malware](http://www.zdnet.com/article/avg-and-rising-signatures-update-detects-windows-files-as-malware/). Hell, some of them even [mark an empty C# app as a virus](https://www.virustotal.com/#/file-analysis/YTZmMzQzOGE5YWM5MGFkZmM3M2U5OTI1MWI1OGU3YzI6MTUxNDgyMTMyMA==)!

**Comment by herrvigg** [comment]
Nice of you! Malware detection on windows seems very bad indeed. It's a bit sad to be forced to remove some features but i think your change will help having people using it more without fear, so that's great! :)

**Comment by herrvigg** [comment]
@SC2Mitch why did you downvote poma's comment? He explained everything, it seems clear it doesn't come from the app and he even fixed it immediately. What else do you expect? If you want to pay for the certificate then go ahead, everyone will be happy.

**Comment by kilbasar** [comment]
FYI this is happening again with latest v2.0.2 HotsApiUploaderSetup.exe and latest Chrome 67.0.3396.99. Confirmed that previous version v2.0.1 is not blocked by Chrome.
